### ISSUE TITLE
Configurable response parsing

### ISSUE THREAD

**Issue by joelvh** [molybdenum-99/tlaw#6]
Hi @zverok!

Came across your projects through one of your blog posts and it seems we have several project ideas in common. I've been developing DSLs for configuring pipelines for data processing, and in that project, my intention is to build up an abstract data model that can utilize various implementations when running each job.

One of the aspects of the pipeline is to define sources, and an API DSL such as TLAW is exactly what I've envisioned. However, there are some aspects of TLAW that are not very configurable (such as processing the response). Specifically, a use case is to stream the response through the pipeline of transforms and so on.

I'd be interested in leveraging the DSL work you've done to define the API client, and abstract out some aspects such as response processing.

Are you open to this kind of contribution?

Thanks!

~Joel

**Comment by zverok** [comment]
@joelvh In fact, I am! TLAW is in search-and-experiment stage, and while using it myself for various cases I've also grown a suspicion that response processing is either not as useful as I've hoped, or at least should be "opt-in" thing. Probably something like Rack's/Faraday's "middleware", or something. Probably even that request construction DSL is what TLAW is about, and this response processing trickery could be separated to completely another gem (and in fact, it can be done as a Faraday middleware, probably).

So yeah, I am pretty open to any contributions coming from practice!

**Comment by joelvh** [comment]
OK, great. I will work with what you've established with the DSL (which is really awesome!) and probably abstract out aspects related to instantiating and composing the API client behavior.

Simply forking the repo, running `bundle install` and then `bundle exec rspec spec` shows 3 tests failing.

What's the proper way to run the tests, or is Ruby 2.5 not supported?

Thanks.

```
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
....No need to use its_call without arguments, just it {} will work
F...................................................................No need to use its_call without arguments, just it {} will work
FNo need to use its_call without arguments, just it {} will work
F..........................No need to use its_call without arguments, just it {} will work
..No need to use its_call without arguments, just it {} will work
..No need to use its_call without arguments, just it {} will work
.....................................

Failures:

  1) TLAW::API.define () should to send TLAW::DSL::APIWrapper.new and to send #<InstanceDouble(TLAW::DSL::APIWrapper) (anonymous)>.define
     Failure/Error:
       is_expected.to send_message(DSL::APIWrapper, :new).with(api_class).returning(wrapper)
         .and send_message(wrapper, :define)

     NoMethodError:
       undefined method `call' for nil:NilClass
     # ./spec/tlaw/api_spec.rb:11:in `block (3 levels) in <module:TLAW>'

  2) TLAW::Namespace instance #<endpoint> () should to send #<(unnamed endpoint class): call-sequence: some_ep(foo: nil); docs: .describe>.new and to send #<InstanceDouble(#<(unnamed endpoint class): call-sequence: some_ep(foo: nil); docs: .describe>) (anonymous)>.call
     Failure/Error:
       is_expected
         .to send_message(endpoint_class, :new).returning(endpoint)
         .and send_message(endpoint, :call).with(foo: 'bar')

     NoMethodError:
       undefined method `call' for nil:NilClass
     # ./spec/tlaw/namespace_spec.rb:131:in `block (4 levels) in <module:TLAW>'

  3) TLAW::Namespace instance #<endpoint> initial params () should to send #<(unnamed endpoint class): call-sequence: some_ep(foo: nil); docs: .describe>.new and to send #<InstanceDouble(#<(unnamed endpoint class): call-sequence: some_ep(foo: nil); docs: .describe>) (anonymous)>.call
     Failure/Error:
       is_expected
         .to send_message(endpoint_class, :new).with(apikey: 'foo').returning(endpoint)
         .and send_message(endpoint, :call).with(foo: 'bar')

     NoMethodError:
       undefined method `call' for nil:NilClass
     # ./spec/tlaw/namespace_spec.rb:140:in `block (5 levels) in <module:TLAW>'
```

**Comment by zverok** [comment]
> Simply forking the repo, running bundle install and then bundle exec rspec spec shows 3 tests failing.

Ugh, sorry, I forgot to push latest commit (pushed now) when I updated my experimental `saharspec` RSpec addon. Spec should work on the latest commit, checked on Ruby 2.5 too.

**Comment by joelvh** [comment]
@zverok I didn't see you had some commits on master that I needed to rebase. Tests pass now. Thanks!
